# Generated by Django 6.0.1 on 2026-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_blogpost_published_at_blogpost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(upload_to='blog/banner/'),
        ),
    ]
