# Generated by Django 6.0.1 on 2026-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_blogpost_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydetail',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
